services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./certbot/shared_certs:/data/custom_ssl

  certbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certbot
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/var/www/html:/var/www/html
      - ./certbot/oci_credentials:/root/.oci:ro
      - ./certbot/scripts:/scripts
      - ./certbot/shared_certs:/shared_certs
    entrypoint: >
      sh -c '
        if [ ! -f /etc/letsencrypt/live/$CERT_NAME/fullchain.pem ]; then
          echo "[INFO] Certificado no existe. Generando por primera vez..."
          certbot certonly \
            --authenticator dns-oci \
            --email $EMAIL \
            -d $DOMAIN \
            -d *.$DOMAIN \
            --agree-tos \
            --non-interactive \
            --dns-oci-propagation-seconds 300 \
            --cert-name $CERT_NAME
        else
          echo "[INFO] Certificado ya existe. No se ejecuta certonly inicial."
        fi;
        crontab /scripts/cronjob && crond -f'
