services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./certbot/shared_certs:/data/custom_ssl
    networks:
      - web

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    entrypoint: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web

  certbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/var/www/html:/var/www/html
      - ./certbot/oci_credentials:/root/.oci:ro
      - ./certbot/scripts:/scripts
      - ./certbot/shared_certs:/shared_certs
    entrypoint: /scripts/entrypoint.sh
    networks:
      - web

networks:
  web:
    driver: bridge
